# Generated by Django 4.2.1 on 2023-05-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_asistenteeducacion_contrato_docente_subvencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='bienios_cumplidos',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='jubilado',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='reemplazando',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='renuncia_presentada',
        ),
        migrations.AddField(
            model_name='docente',
            name='calidad_nombramiento',
            field=models.CharField(blank=True, choices=[('titular', 'Titular'), ('contrata', 'Contrata'), ('reemplazo', 'Reemplazo'), ('jubilado', 'Jubilado'), ('cese', 'Cese'), ('renuncia', 'Renuncia'), ('termino_contrato', 'Termino Contrato')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='tramo_cpeip',
            field=models.CharField(blank=True, choices=[('acceso', 'Acceso'), ('inicial', 'Inicial'), ('temprano', 'Temprano'), ('avanzado', 'Avanzado'), ('experto 1', 'Experto 1'), ('experto 2', 'Experto 2')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_servicio', models.DateField(blank=True, null=True)),
                ('num_decreto_nombramiento_titular', models.IntegerField(blank=True, null=True)),
                ('fecha_decreto_nombramiento_titular', models.DateField(blank=True, null=True)),
                ('num_decreto_nombramiento', models.IntegerField(blank=True, null=True)),
                ('fecha_nombramiento_decreto', models.DateField(blank=True, null=True)),
                ('fecha_nombramiento_desde', models.DateField(blank=True, null=True)),
                ('fecha_nombramiento_hasta', models.DateField(blank=True, null=True)),
                ('fecha_certificado_vacaciones_progresivas', models.DateField(blank=True, null=True)),
                ('anos_cotizados_afp', models.IntegerField(blank=True, null=True)),
                ('dias_vacaciones_progresivas', models.IntegerField(blank=True, null=True)),
                ('dias_vacaciones_acumuladas', models.IntegerField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Bienio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_decreto_ultimo_bienio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_decreto', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_bienio_reconocido', models.DateField(blank=True, null=True)),
                ('proximo_bienio', models.DateField(blank=True, null=True)),
                ('dias_acumulados', models.IntegerField(blank=True, null=True)),
                ('sueldo_total_haberes', models.FloatField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.docente')),
            ],
        ),
    ]
