# Generated by Django 4.2.1 on 2023-05-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_alter_establecimiento_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='rol',
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.rol')),
            ],
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimiento_encargado', to='establecimiento.asignacion'),
        ),
    ]
