# Generated by Django 4.2.1 on 2023-05-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_remove_docente_bienios_cumplidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimiento.contrato'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.persona'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='rol',
            field=models.CharField(blank=True, choices=[('daem (s)', 'DAEM (s)'), ('director daem', 'Director DAEM'), ('director(a)', 'Director(a)'), ('docencia directiva', 'Docencia directiva'), ('docente', 'Docente'), ('docente (reemplazo)', 'Docente (reemplazo)'), ('docente aula', 'Docente de aula'), ('docente aula (reemplazo)', 'Docente de aula (reemplazo)'), ('docente educación diferencial', 'Docente Educación Diferencial'), ('docente educación especial', 'Docente Educación Especial'), ('docente pie (reemplazo)', 'Docente PIE (reemplazo)'), ('docente proyecto pie', 'Docente Proyecto PIE'), ('educador(a) tradicional', 'Educador(a) tradicional'), ('educador tradicional lengua indigena', 'Educador tradicional lengua indígena'), ('educadora de parvulos (reemplazo)', 'Educadora de párvulos (reemplazo)'), ('educadora tradicional lengua indigena', 'Educadora tradicional lengua indígena'), ('encargado estadistica', 'Encargado Estadística'), ('encargado extraescolar', 'Encargado extraescolar'), ('encargado transporte', 'Encargado transporte'), ('inspector general', 'Inspector general'), ('jefe unidad técnico-pedagógica', 'Jefe unidad técnico-pedagógica'), ('otra en el establecimiento', 'Otra en el establecimiento'), ('otra fuera del establecimiento', 'Otra fuera del establecimiento'), ('orientador', 'Orientador'), ('planta directiva', 'Planta directiva'), ('profesor(a) encargado(a) del establecimiento', 'Profesor(a) encargado(a) del establecimiento'), ('reemplazante', 'Reemplazante'), ('técnico-pedagógica', 'Técnico-pedagógica'), ('UTP comunal', 'UTP comunal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='subvencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimiento.subvencion'),
        ),
    ]
