# Generated by Django 4.2.1 on 2023-05-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_alter_docente_contrato_alter_docente_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='jubilado',
            field=models.BooleanField(default=False),
        ),
    ]
