# Generated by Django 4.2.1 on 2023-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_docente_bienios_cumplidos_alter_docente_jubilado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='renuncia_presentada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
